name: Update Crime Map Data

on:
  schedule:
    - cron: '0 23 * * *'  # Всеки ден в 02:00 българско време (23:00 UTC)
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pandas folium

    - name: Run update scripts
      run: |
        python scripts/fetch_bulletins.py
        python scripts/extract_cases.py
        python scripts/geocode.py

    - name: Install dependencies
      run: pip install -r requirements.txt
  
    - name: Commit updated data 
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add data/*.csv map/interactive_map.html docs/interactive_map.html || true
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Automated update of crime data"
          git push
        fi
